apiVersion: v1
kind: Pod
metadata:
  name: login-app
  labels:
    app: login-app
spec:
  containers:
    - name: login-app
      image: login:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 4001