apiVersion: v1
kind: Pod
metadata:
  name: rent-app
  labels:
    app: rent-app
spec:
  containers:
    - name: rent-app
      image: rent:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8087